language: node_js
node_js:
  - "10"
cache:
  directories:
    - ${SERVICE_PATH}/node_modules
deploy:
  - provider: s3
  - provider: codedeploy
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: "S3 Bucket"
    application: MyApp
    deployment_group: MyDeploymentGroup
install:
  - npm install -g serverless
  - travis_retry npm install
  - cd ${SERVICE_PATH}
  - travis_retry npm install
  - cd -
before-script:
  - cd secure-app-server
script:
  - serverless deploy
  - cd -