language: node_js
node_js:
  - "10"
cache:
  directories:
    - secure-app-client/node_modules
    - secure-app-server/node_modules
before_install:
  - pip install awscli
install:
  - npm install -g serverless
  - cd secure-app-client
  - npm install
  - cd -
  - cd secure-app-client
  - npm install
  - cd -
script:
  - cd secure-app-server
  - serverless deploy
  - cd -
  - cd secure-app-client
  - npm run build
  - npm run deploy
  - cd -