language: node_js
node_js:
  - "10"
before_install:
  - pip install awscli
install:
  - npm install -g serverless
  - cd ${SERVICE_PATH}
  - npm install
  - npm install -s chalk
  - cd -
script:
  - cd secure-app-server
  - serverless deploy
  - cd -
  - cd secure-app-client
  - npm run build
  - npm run deploy
  - cd -