language: node_js
node_js:
  - "10"
cache:
  directories:
    - ${SERVICE_PATH}/node_modules
install:
  - npm install -g
  - cd -
script:
  - cd secure-app-server
  - serverless deploy
  - cd -
  - cd secure-app-client
  - npm run build
  - npm run deploy
  - cd -